### ISSUE TITLE
Create initial d10/11 module

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/gutenberg-ai-tools#1]
- Drupal 10/11 module
- Extends [Gutenberg module](https://www.drupal.org/project/gutenberg)
- The module defines a custom [Gutenberg Block](https://git.drupalcode.org/project/gutenberg/-/tree/3.0.x/modules/example_blocks?ref_type=heads)

**Comment by danrod96** [comment]
I implemented custom functionality for enabling the new "AI Block", I still need to work on the editor.js to integrate this new component in the Gutenberg editor and work in the OpenAI integration (I'm using a service provided by the contrib module https://www.drupal.org/project/openai)
![Screenshot from 2024-07-22 11-40-16](https://github.com/user-attachments/assets/92517eee-79cc-4559-86c6-9e2f17dc8204)
