### ISSUE TITLE
Create a Gutenberg block for creating Generative AI prompt/response

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/gutenberg-ai-tools#2]
Goal is to create something similar to this:

- https://shop.gutenberghub.com/product/ai-writer

The new block will:

1. Present the user with a text area input that allows the user to enter a prompt.
2. The user can input any text into the textarea and submit the text.
3. The text is sent to OpenAI GPT4 API endpoint.
4. The response from OpenAI is added to Gutenberg editor body as gutenberg-compliant code/text.

**Comment by danrod96** [comment]
This is in the works, I finally have all the basic structure for the AI Block, I can add it from the editor, next step is to send the question to OpenAI and render the answer in the main content div, I'll rely on the OpenAI Drupal Module which already has a service that I'll try to use it from the Gutenberg Block (Perhaps I'll need to create a custom REST Endpoint for that)

![gutenberg-ai-block](https://github.com/user-attachments/assets/72c641d8-7dcc-473b-835d-88b563e0c072)

**Comment by danrod96** [comment]
@ymdahi I refactored the AI Block to move the OpenAI prompt in the block settings.

![gutenberg-ai-block2](https://github.com/user-attachments/assets/9aa879cc-78f7-41a9-a26f-79001ec493bd)


Pending: Integration with OpenAI (ongoing)

**Comment by danrod96** [comment]
Hi @ymdahi this is done, I've managed to create an initial release of this module that actually works (screenshots included), there's some issues that need to be fixed, the onBlur event is not working as I expected, I'll look on that later.
Good stuff !!
![Screenshot from 2024-08-21 22-36-43](https://github.com/user-attachments/assets/7e44cd45-014e-4dc9-8c87-e8073a38ba52)
![Screenshot from 2024-08-21 22-35-13](https://github.com/user-attachments/assets/01a01e51-bb4f-449a-8634-7518b76372c5)
